name: Rectangle
description: |
  Rectangle is a python package for computational deconvolution.
  Rectangle presents a novel approach to second-generation deconvolution, characterized by hierarchical processing, an estimation of unknown cellular content and a significant reduction in data volume during signature matrix computation.
project_home: https://github.com/ComputationalBiomedicineGroup/Rectangle
documentation_home: https://rectanglepy.readthedocs.io
tutorials_home: https://rectanglepy.readthedocs.io/notebooks/example.html
install:
  pypi: rectanglepy
license: MIT
tags:
  - rna-seq
  - deconvolution
version: v0.1.6
authors:
  - bernheder
test_command: |
  pip install ."[dev,test]" && pytest
