name: spatialproteomics
description: |
  Spatialproteomics is an interoperable toolbox for analyzing highly multiplexed fluorescence image data.
  This analysis involves a sequence of steps, including segmentation, image processing,
  marker quantification, cell type classification, and neighborhood analysis.
project_home: https://github.com/sagar87/spatialproteomics
documentation_home: https://sagar87.github.io/spatialproteomics
tutorials_home: https://sagar87.github.io/spatialproteomics/notebooks/ExampleWorkflow.html
install:
  pypi: spatialproteomics
tags:
  - spatial-omics
  - spatial-proteomics
  - multiplex imaging
  - spatialdata
  - pipeline
license: MIT
version: v0.7.0
authors:
  - MeyerBender
  - sagar87
test_command: pip install ".[all,dev]" && pytest
