name: scDataLoader
description: |
  A dataloader for large single cell databases like cellxgene.
  Does weighted random sampling, downloading and preprocessing.
  works with anndata, zarr, and h5ad files.
project_home: https://github.com/jkobject/scDataLoader
documentation_home: https://www.jkobject.com/scDataLoader/
publications:
  - 10.1101/2024.07.29.605556
install:
  pypi: scdataloader
tags:
  - dataloader
  - single cell
  - RNAseq
  - pytorch
  - lightning
  - cellxgene
  - preprocessing
license: MIT
version: v1.2.2
authors:
  - jkobject (jeremie kalfon)
test_command: pip install . && make test
